# Generated by Django 4.1.6 on 2023-04-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/topics/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.topic')),
            ],
        ),
    ]
