# Generated by Django 4.1.6 on 2023-04-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_topicimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
